# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170714_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='width_field', null=True, upload_to='', width_field='height_field'),
        ),
    ]
