# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170714_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='width_field', null=True, upload_to=posts.models.upload_location, width_field='height_field'),
        ),
    ]
